package com.pelikbetul;
// Generated Dec 3, 2017 4:04:08 PM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;








/**
 * Books generated by hbm2java
 */
//Kena letak ni baru jadi utk jaxb , webservices

@XmlRootElement(namespace = "com.pelikbetul")
@XmlAccessorType(XmlAccessType.FIELD)
public class Books  implements java.io.Serializable {


     private Integer bookid;
     private String btitle;
     private String bisbn;
     public int quantity;
     public double price;
     

    public Books() {
        bookid=0;
        btitle="";
        bisbn="";
        quantity=0;
        price=0.0;
    }

    public Books(int bookid,String btitle, String bisbn, int quantity, double price) {
       this.btitle = btitle;
       this.bisbn = bisbn;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getBookid() {
        return this.bookid;
    }
    
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
    public String getBtitle() {
        return this.btitle;
    }

    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }
    public String getBisbn() {
        return this.bisbn;
    }
   
    
    public void setBisbn(String bisbn) {
        this.bisbn = bisbn;
    }
  
    public int getQuantity() {
        return this.quantity;
    }
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
   
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
 
   
   
 



}


