package com.pelikbetul;
// Generated Dec 3, 2017 4:04:08 PM by Hibernate Tools 4.3.1

import java.util.*;
import java.util.List;




/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer bookid;
     private String btitle;
     private String bisbn,selectedisbn;
     public int quantity;
     public double price;
     

    public Books() {
    }

    public Books(int bookid,String btitle, String bisbn, int quantity, double price) {
       this.btitle = btitle;
       this.bisbn = bisbn;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getBookid() {
        return this.bookid;
    }
    
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
    public String getBtitle() {
        return this.btitle;
    }
     public List<Books> getAllBooks() {
        List<Books> allBooks = new ArrayList<Books>();
        StoreController dao = new StoreController();
        allBooks = dao.getAllBooks();
        return allBooks;
    }
    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }
    public String getBisbn() {
        return this.bisbn;
    }
    public void fullInfo() {
        StoreController dao = new StoreController();
        List<Books> lb = dao.getBooksByIsbn(selectedisbn);
        System.out.println(lb.get(0).btitle);
        this.bisbn = lb.get(0).bisbn;
        this.quantity = lb.get(0).quantity;
        this.price = lb.get(0).price;
    }
    
    public void setBisbn(String bisbn) {
        this.bisbn = bisbn;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
     public String getSelectedisbn() {
        return selectedisbn;
    }
 
    public void setSelectedisbn(String selectedname) {
        this.selectedisbn = selectedname;
    }
    public void clear(){
        btitle=null;
        bisbn = null;
        quantity=0;
        price = 0;
        
    }
 



}


