package com.pelikbetul;
// Generated Dec 3, 2017 4:04:08 PM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;



/**
 * Payment generated by hbm2java
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "payment")
public class Payment  implements java.io.Serializable {


     private Integer paymentid;
     private int custid;
     private double totalprice;

    public Payment() {
        paymentid=0;
        custid=0;
        totalprice=0.0;
    }

    public Payment(int paymentid,int custid, double totalprice) {
       this.custid = custid;
       this.totalprice = totalprice;
    }
    
   
    public Integer getPaymentid() {
        return this.paymentid;
    }
    
    public void setPaymentid(Integer paymentid) {
        this.paymentid = paymentid;
    }
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }
    public double getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(double totalprice) {
        this.totalprice = totalprice;
    }




}


