package com.pelikbetul;
// Generated Dec 3, 2017 4:04:08 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer paymentid;
     private int custid;
     private double totalprice;

    public Payment() {
    }

    public Payment(int custid, double totalprice) {
       this.custid = custid;
       this.totalprice = totalprice;
    }
   
    public Integer getPaymentid() {
        return this.paymentid;
    }
    
    public void setPaymentid(Integer paymentid) {
        this.paymentid = paymentid;
    }
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }
    public double getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(double totalprice) {
        this.totalprice = totalprice;
    }




}


